0901/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

0901/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

0901/crud/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

0901/crud/articles/views.py
from lib2to3.pgen2.token import TILDE
from re import A
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article()
    article.title = title
    article.content = content
    article.save()

    # article = Article(title=title, content=content)
    # article.save()

    # Article.objects.create(title=title, content=content)


    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    if request.method == "POST":
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    if request.method == "POST":
        article = Article.objects.get(pk=pk)
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        return redirect('articles:detail', article.pk)

0901/crud/articles/templates/articles/detail.html
{% extends 'base.html' %} {% block content %}
<h1>detail</h1>
<h2>{{ article.pk}}th article</h2>
<h2>title: {{ article.title}}</h2>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button>delete</button>
</form>
<a href="{% url 'articles:edit' article.pk %}">edit</a>
{% comment %}
<textarea name="content" id="" cols="30" rows="10">
{{article.content}}</textarea
>
{% endcomment %}
<a href="{% url 'articles:index' %}">to index</a>

{% endblock content %}

0901/crud/articles/templates/articles/edit.html
{% extends 'base.html' %} {% block content %}
<h1>edit</h1>
<a href="{% url 'articles:index' %}">back</a>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <label for="title">title: </label>
  <input type="text" name="title" id="title" value="{{article.title}}" /><br />
  <label for="content">content: </label>
  <input
    type="text"
    name="content"
    id="content"
    value="{{article.content}}"
  /><br />
  <input type="submit" />
</form>

{% endblock content %}

0901/crud/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>index</h1>
    <a href="{% url 'articles:new' %}">create new content</a>
    {% for article in articles %}
    <a href="{% url 'articles:detail' article.pk %}">
      <p>title: {{article.title}}</p>
    </a>
    <p>content: {{article.content}}</p>
    <hr />

    {% endfor %}
  </body>
</html>

0901/crud/articles/templates/articles/new.html
{% extends 'base.html' %} {% block content %}
<h1>new</h1>
<a href="{% url 'articles:index' %}">back</a>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <label for="title">title: </label>
  <input type="text" name="title" id="title" /><br />
  <label for="content">content: </label>
  <input type="text" name="content" id="content" /><br />
  <input type="submit" />
</form>

{% endblock content %}

0901/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>